name = "dns-checker"
main = "src/index.ts"
compatibility_date = "2024-06-03"
compatibility_flags = ["nodejs_compat"]


[build]
  command = "npm run build"
  cwd = "."

[dev]
  ip = "0.0.0.0"
  port = 8787
  local_protocol = "http"
